version: '3.8'

services:
  sms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-app
    stdin_open: true
    tty: true
    volumes:
      # Mount thư mục hiện tại để có thể chỉnh sửa code mà không cần rebuild
      - .:/app
    environment:
      - PYTHONPATH=/app

